//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DieteticaG3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle
    {
        public int Id { get; set; }
        public int codProd { get; set; }
        public int numPed { get; set; }
        public int cantidad { get; set; }
    
        public virtual Pedido Pedido { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
